# Generated by Django 5.1.1 on 2025-03-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_id_alter_campaign_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_stripe_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
